---
regions:
  - "eu-west-1"
account-blacklist:
- 1234567890

resource-types:
  targets:
  - S3Object
  - S3Bucket
  excludes:
  - IAMRole

accounts:
  555133742:
    resource-types:
      targets:
      - S3Bucket
    filters:
      IAMRole:
      - "uber.admin"
      IAMRolePolicyAttachment:
      - "uber.admin -> AdministratorAccess"
